service: templates\nodejs
frameworkVersion: "3"

#provider:
#  name: yandex-cloud
#  runtime: nodejs16
#  httpApi:
#    payload: '1.0'
provider:
  name: aws
  runtime: nodejs16.x

plugins:
#  - "@yandex-cloud/serverless-plugin"
  - serverless-offline

package:
  patterns:
    - '!**'
    - package.json
    - package-lock.json
    - dist/*.js

functions:
  simple:
    handler: dist/index.hello
    memorySize: 128
    timeout: '5'
    account: function-sa
    events:
      - http:
          method: get
          path: /

#resources:
#  trigger-sa:
#    type: yc::ServiceAccount
#    roles:
#      - serverless.functions.invoker
#  function-sa:
#    type: yc::ServiceAccount
#    roles:
#      - editor
