service: next-webpack-plugin

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: ap-southeast-2

  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: /

  nested:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: /nested/{any+}

  static:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: /_next/static/{any+}

  fallback:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: /{any+}

custom:
  serverless-offline:
    noPrependStageInUrl: true