service: next-webpack-plugin

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x


plugins:
  - serverless-offline
  - serverless-plugin-typescript
  # - serverless-static


functions:
  lambda:
    handler: lib/lambda.handler
    events:
      - http:
          method: GET
          path: /api/{any+}
  lambda1:
    handler: lib/lambda.handler
    events:
      - http:
          method: POST
          path: /api/{any+}

custom:
  serverless-offline:
    noPrependStageInUrl: true
  # static:
  #   path: ./static # select the folder you want to serve
  #   port: 8000 # select a specific port
